Add a column for number of failed tests(#170)
nathan-weinberg/jeeves pull request #171
Opened 2020-12-15 10:54 UTC by itzikb

A patch to add the number of failed tempest test for the last build of each job

2020-12-15 14:41 UTC, agarcia64 approved these changes
Tested on my machine, everything is working as expected. In addition, the code looks clean and consistent. Looks good to me!

2020-12-15 15:53 UTC, amodi5 commented on report.py
> -
nit: add the blank line

2020-12-15 15:53 UTC, amodi5 reviewed
LGTM!

2020-12-15 17:17 UTC, nathan-weinberg requested changes
Two small requests:
1. Could we implement this for reminders as well?
2. If there value is not "N/A", could we link to the tempest results page on Jenkins? (if this is non-trivial, it does not need to block merging, but please open an RFE to implement this feature later)

2020-12-16 08:45 UTC, itzikb commented on report.py
> -
Done

2020-12-16 08:46 UTC, itzikb commented
Done
> Two small requests:
> 
> 1. Could we implement this for reminders as well?
> 2. If there value is not "N/A", could we link to the tempest results page on Jenkins? (if this is non-trivial, it does not need to block merging, but please open an RFE to implement this feature later)

2020-12-16 14:50 UTC, nathan-weinberg approved these changes
LGTM! Will leave up for now so others can review but will merge by EOD :+1:

2020-12-16 22:21 UTC, merged