Fixes job covered calculations
nathan-weinberg/jeeves pull request #204
Opened 2021-04-08 13:57 UTC by ciecierski

Use has_blockers from blockers.py instead of exception-based approach

2021-04-08 20:24 UTC, nathan-weinberg reviewed
Worked for Enterprise report, will wait to hear from others

2021-04-09 11:35 UTC, ciecierski commented
Moving to WIP status. It won't work in situation when there are missing job names in blockers file, for UNSTABLE and FAILED jobs.

2021-04-13 02:29 UTC, nathan-weinberg requested changes
One nit but otherwsie LGTM, @agarcia64 does this resolve your issue?

2021-04-13 02:29 UTC, nathan-weinberg commented on jeeves/blockers.py
>  		returns False otherwise
```suggestion
	''' returns True if job_name exists in blockers and has any defined blockers
		returns False otherwise
```

2021-04-13 17:35 UTC, agarcia64 approved these changes
Just tested on my machine, everything is working as expected and the code looks good to me!

2021-04-14 12:45 UTC, nathan-weinberg approved these changes

2021-04-14 12:45 UTC, merged